
on:
  push:
    branches:
      - main
      
      
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      - name: "Login to Docker"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOCKEN }}
        
      - name: "Building Docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task2 .
        
      - name: "Pushing the image"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/task2
        
